#Check for a plugin update
Update-check: true
Options:
  #LANGUAGES: EN ES
  Language: 'EN'
  #Send a message when the player first joins
  First-join: true
  #Send a message when the player joins
  Player-join: true
  #Send a message when the player leaves
  Player-quit: true
  #Send a list of messages when the player joins, example:
  #- '&m                                             '
  #- '&6&lWelcome to &c&lserver &a&l{player}'
  #- '&m                                             '
  Motd: true
  #Teleport a player when he first joined
  Teleport-to-firstjoin: true
  #Teleport a player when he joins
  Teleport-to-join: true
  #Teleport a player when he falls into the void
  VoidSpawn: true
  # whitelist or blacklist
  Worlds-option: 'whitelist'
  #List of worlds
  Worlds:
    - world
  Void-fall: -15
  #Time in Seconds - ONLY 1.8.x
  Spawn-Cooldown: 15
Sounds:
  # You can check here the whole list of minecraft sounds.
  # 1.8.x - 1.12.x https://pastebin.com/W8ZnDx3V
  # 1.13.x - 1.14.x https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  #How to use Sound;Volume(10);pitch(recommended leave it in 2)
  Spawn: true
  Spawn-Sound: ENDERDRAGON_GROWL;10;2
  Admin-join: true
  Admin-join-Sound: ENDERDRAGON_DEATH;10;2
  Join: true
  Join-Sound: NOTE_PLING;10;2
  First-join: true
  First-join-Sound: WITHER_SPAWN;10;2
  Voidfall: true
  Voidfall-Sound: EXPLODE;10;5
Fireworks:
  Join: true
  First-join: true
  Spawn: true
Permissions:
  Update-check: 'myspawn.update-check'
  Admin-join: 'myspawn.admin'
  Reload: 'myspawn.reload'