#Check for a plugin update
Update-check: true
Options:
  #LANGUAGES: EN ES
  Language: 'EN'
  #Send a message when the player first joins
  First-join: true
  #Send a message when the player joins
  Player-join: true
  #Send a message when the player leaves
  Player-quit: true
  #Send a list of messages when the player joins, example:
  #- '&m                                             '
  #- '&6&lWelcome to &c&lserver &a&l{player}'
  #- '&m                                             '
  Motd: true
  #Teleport a player when he joins for the first time
  Teleport-to-firstjoin: true
  #Teleport a player when he joins
  Teleport-to-join: true
  #Teleport a player when he falls into the void
  VoidSpawn: true
  # whitelist or blacklist
  Worlds-option: 'whitelist'
  #List of worlds to teleport the player when he voidfalls
  # whitelist: only the worlds in the list
  # blacklist: all the worlds except the ones in the list
  #Example: Worlds:
  # - world
  # - world_nether
  # - world_the_end
  Worlds:
    - world
  #The amount of blocks before the player falls into the void
  # Void-fall: -15 for 1.8.x
  # Void-fall: -95 for 1.14.x+ in this version change due to the new world generation
  # Try by yourself
  Void-fall: -95
  # Cooldown for the /spawn command
  # Leave it in true if you want cooldown for the /spawn command
  Cooldown: true
  #Time in Seconds to teleport the player when uses the /spawn command
  Spawn-Cooldown: 15
Sounds:
  # You can check here the whole list of minecraft sounds.
  # 1.8.x - 1.12.x https://pastebin.com/W8ZnDx3V
  # 1.13.x - 1.14.x https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  #How to use Sound;Volume(1.0f);pitch(recommended leave it in 1.0f)
  #Example: BLOCK_ANVIL_LAND;1.0f;1.0f (its sound a distance of 16 blocks, with the original tone)
  #Example: BLOCK_ANVIL_LAND;0.5f;0.5f (its sound a distance of 8 blocks, with a Lower pitch, slower)
  Spawn: true
  Spawn-Sound: ENTITY_ENDER_DRAGON_GROWL;2;4
  Admin-join: true
  Admin-join-Sound: BLOCK_ANVIL_LAND;3;5
  Join: true
  Join-Sound: BLOCK_NOTE_BLOCK_PLING;7;5
  First-join: true
  First-join-Sound: ENTITY_PLAYER_LEVELUP;7;5
  Voidfall: true
  Voidfall-Sound: ENTITY_GENERIC_EXPLODE;7;5
Fireworks:
  #Fireworks when the player joins
  Join:
    Enabled: true
    # Fireworks power
    # The power of the fireworks, from 1 to 3
    Power: 1
    #Fireworks colors
    # List of named colors to use
    # "RED", "GREEN", "BLUE", "YELLOW", "PURPLE", "WHITE", "BLACK", "ORANGE", "PINK", "CYAN", "MAGENTA", "LIME", "LIGHT_BLUE", "BROWN", "LIGHT_GRAY", "GRAY"
    # You can use the color names or Hexadecimal values
    #  - "#FF5733"   # Hexadecimal color
    #  - "RED"       # Named color
    #  - "#00FF00"   # Hexadecimal color
    Colors:
      - "RED"
      - "GREEN"
    # Fireworks type
    # You can use the type names or the ID
    # Example: - "BALL" or - 0
    # Example: - "BURST" or - 1
    # Example: - "STAR" or - 2
    # Example: - "CREEPER" or - 3
    # Example: - "BALL_LARGE" or - 4
    Type: "BALL"
    # Fireworks trail
    # Defaults to false if not specified
    Trail: true
    # Fireworks flicker
    # Defaults to false if not specified
    Flicker: false
  #Fireworks when the player first joins
  First-join:
    Enabled: true
    Power: 2
    Colors:
      - "BLUE"
      - "YELLOW"
    Type: "STAR"
    Trail: true
    Flicker: false
  #Fireworks when the player uses the /spawn command
  Spawn:
    Enabled: true
    Power: 3
    Colors:
      - "PURPLE"
      - "WHITE"
    Type: "BURST"
    # Fireworks trail
    # Defaults to false if not specified
    Trail: true
    # Fireworks flicker
    # Defaults to false if not specified
    Flicker: false
Permissions:
  Update-check: 'myspawn.update-check'
  Admin-join: 'myspawn.admin'
  Reload: 'myspawn.reload'
  Set-Spawn: 'myspawn.setspawn'
  Set-FirstSpawn: 'myspawn.setfirstspawn'
  Bypass-Cooldown: 'myspawn.bypass-cooldown'