#Check for a plugin update
Update-check: true
Options:
  #LANGUAGES: EN ES
  Language: 'EN'
  #Send a message when the player first joins
  First-join: true
  #Send a message when the player joins
  Player-join: true
  #Send a message when the player leaves
  Player-quit: true
  #Send a list of messages when the player joins, example:
  #- '&m                                             '
  #- '&6&lWelcome to &c&lserver &a&l{player}'
  #- '&m                                             '
  Motd: true
  #Teleport a player when he first joined
  Teleport-to-firstjoin: true
  #Teleport a player when he joins
  Teleport-to-join: true
  #Teleport a player when he falls into the void
  VoidSpawn: true
  # whitelist or blacklist
  Worlds-option: 'whitelist'
  #List of worlds
  Worlds:
    - world
  #The amount of blocks before the player falls into the void
  # Void-fall: -15 for 1.8.x
  # Void-fall: -95 for 1.14.x+ in this version change due to the new world generation
  # Try by yourself
  Void-fall: -95
  #Time in Seconds - ONLY 1.8.x
  Spawn-Cooldown: 15
Sounds:
  # You can check here the whole list of minecraft sounds.
  # 1.8.x - 1.12.x https://pastebin.com/W8ZnDx3V
  # 1.13.x - 1.14.x https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  #How to use Sound;Volume(1.0f);pitch(recommended leave it in 1.0f)
  #Example: BLOCK_ANVIL_LAND;1.0f;1.0f (its sound a distance of 16 blocks, with the original tone)
  #Example: BLOCK_ANVIL_LAND;0.5f;0.5f (its sound a distance of 8 blocks, with a Lower pitch, slower)
  Spawn: true
  Spawn-Sound: ENTITY_ENDER_DRAGON_GROWL;1.0f;1.0f
  Admin-join: true
  Admin-join-Sound: BLOCK_ANVIL_LAND;1.0f;1.0f
  Join: true
  Join-Sound: BLOCK_NOTE_BLOCK_PLING;1.0f;1.0f
  First-join: true
  First-join-Sound: WITHER_SPAWN;1.0f;1.0f
  Voidfall: true
  Voidfall-Sound: ENTITY_GENERIC_EXPLODE;1.0f;1.0f
Fireworks:
  Join: true
  First-join: true
  Spawn: true
Permissions:
  Update-check: 'myspawn.update-check'
  Admin-join: 'myspawn.admin'
  Reload: 'myspawn.reload'
  Set-Spawn: 'myspawn.setspawn'
  Set-FirstSpawn: 'myspawn.setfirstspawn'