name: Java CI + Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Extract version from pom.xml
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Read Changelog into a temporary file
        run: |
          # Lee el contenido de Changelog.md y lo guarda en un archivo temporal
          cat Changelog.md > changelog.txt
          # Asegúrate de que el archivo está formateado correctamente
          cat changelog.txt

      - name: Set release notes
        run: |
          # Lee el contenido del archivo temporal y lo pasa como variable
          RELEASE_NOTES=$(<changelog.txt)
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Prepare artifacts
        run: mkdir staging && cp target/*.jar staging

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: ${{ env.NOTES }}
          files: staging/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
