name: Java CI + Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Get version from pom.xml
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set changelog from Changelog.md
        run: |
          {
          echo 'CHANGELOG<<EOF'
          cat Changelog.md
          echo 'EOF'
          } >> "$GITHUB_ENV"
      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Prepare artifacts
        run: mkdir staging && cp target/*.jar staging

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: ${{ env.CHANGELOG }}
          files: staging/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
