name: Java CI + Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Extract version and release notes from pom.xml
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          # Leer el archivo y convertirlo a un formato que respete saltos de línea
          RELEASE_NOTES=$(awk 'BEGIN{ORS="\n"} {gsub(/\n/, "\\n"); print $0}' Changelog.md)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Prepare artifacts
        run: mkdir staging && cp target/*.jar staging

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: ${{ env.RELEASE_NOTES }}
          files: staging/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
