name: Java CI + Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Extract version from pom.xml
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Prepare artifacts
        run: mkdir staging && cp target/*.jar staging

      - name: Create GitHub Release via API
        run: |
          # Reemplaza el siguiente con el tag y las notas
          VERSION="v2.1a27"
          NOTES=$(cat Changelog.md)

          # JSON con la información del release
          JSON_PAYLOAD=$(jq -n \
            --arg tag_name "$VERSION" \
            --arg release_name "Release $VERSION" \
            --arg body "$NOTES" \
            '{
              "tag_name": $tag_name,
              "name": $release_name,
              "body": $body,
              "draft": false,
              "prerelease": false
            }')

          # Llamada a la API de GitHub para crear el release
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD" \
            https://api.github.com/repos/${{ github.repository }}/releases
          
          # Extraer el ID del release recién creado
          RELEASE_ID=$(echo $RESPONSE | jq -r '.id')

          # Subir los archivos .jar a la release
          for file in staging/*.jar; do
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -F "file=@${file}" \
              "https://uploads.github.com/repos/${{ github.repository }}/releases/${RELEASE_ID}/assets?name=$(basename $file)"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}