# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: Extract version from pom.xml
      id: version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Read release notes
      id: notes
      run: |
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
        cat Changelog.md >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    - name: Configure Git user
      run: |
        git config --global user.email "angel.amarillas@proton.me"
        git config --global user.name "Theangel256"
    - name: Create Git tag for release
      run: |
        git tag -a "v${{ env.VERSION }}" -m "Release version ${{ env.VERSION }}"
        git push origin "v${{ env.VERSION }}"
    - name: Prepare artifacts for upload
      run: mkdir staging && cp target/*.jar staging || true
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        release_name: "Release ${{ env.VERSION }}"
        body: ${{ env.RELEASE_NOTES }}
        files: staging/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
